-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 15:50:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ispc_g15b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ispc_g15b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ispc_g15b` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ispc_g15b` ;

-- -----------------------------------------------------
-- Table `ispc_g15b`.`cuarto_año`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispc_g15b`.`cuarto_año` (
  `ID_ESTUDIANTE` INT NOT NULL AUTO_INCREMENT,
  `Apellido` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(15) NOT NULL,
  `E_mail` VARCHAR(40) NULL DEFAULT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `Fecha_De_Nacimiento` DATE NOT NULL,
  `Edad` INT NOT NULL,
  `Teléfono` VARCHAR(11) NULL DEFAULT NULL,
  `Direccion` VARCHAR(30) NULL DEFAULT NULL,
  `Localidad` VARCHAR(20) NULL DEFAULT NULL,
  `Provincia` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ESTUDIANTE`),
  UNIQUE INDEX `E_mail` (`E_mail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispc_g15b`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispc_g15b`.`materia` (
  `ID_MATERIA` INT NOT NULL AUTO_INCREMENT,
  `Espacio` VARCHAR(25) NOT NULL,
  `Profesor` VARCHAR(25) NOT NULL,
  `Detalle` TEXT NULL DEFAULT NULL,
  `Carga_Horaria` INT NOT NULL,
  PRIMARY KEY (`ID_MATERIA`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispc_g15b`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispc_g15b`.`asistencia` (
  `ID_ASISTENCIA` INT NOT NULL AUTO_INCREMENT,
  `ID_ESTUDIANTE` INT NOT NULL,
  `ID_MATERIA` INT NOT NULL,
  `Fecha_Clase` DATE NOT NULL,
  `Asistencia` ENUM('Presente', 'Ausente') NOT NULL,
  `Justificacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ASISTENCIA`),
  INDEX `ID_ESTUDIANTE` (`ID_ESTUDIANTE` ASC) VISIBLE,
  INDEX `ID_MATERIA` (`ID_MATERIA` ASC) VISIBLE,
  CONSTRAINT `asistencia_ibfk_1`
    FOREIGN KEY (`ID_ESTUDIANTE`)
    REFERENCES `ispc_g15b`.`cuarto_año` (`ID_ESTUDIANTE`),
  CONSTRAINT `asistencia_ibfk_2`
    FOREIGN KEY (`ID_MATERIA`)
    REFERENCES `ispc_g15b`.`materia` (`ID_MATERIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispc_g15b`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispc_g15b`.`grupo` (
  `ID_GRUPO` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Grupo` VARCHAR(50) NOT NULL,
  `ID_ESTUDIANTE` INT NOT NULL,
  PRIMARY KEY (`ID_GRUPO`),
  INDEX `ID_ESTUDIANTE` (`ID_ESTUDIANTE` ASC) VISIBLE,
  CONSTRAINT `grupo_ibfk_1`
    FOREIGN KEY (`ID_ESTUDIANTE`)
    REFERENCES `ispc_g15b`.`cuarto_año` (`ID_ESTUDIANTE`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispc_g15b`.`nota_formativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispc_g15b`.`nota_formativa` (
  `ID_NOTA_Formativa` INT NOT NULL AUTO_INCREMENT,
  `ID_ESTUDIANTE` INT NOT NULL,
  `ID_MATERIA` INT NOT NULL,
  `Nota` INT NULL DEFAULT NULL,
  `Fecha_Exámen` DATE NOT NULL,
  `Tipo_Exámen` ENUM('Recuperatorio', 'Final') NOT NULL,
  PRIMARY KEY (`ID_NOTA_Formativa`),
  INDEX `ID_ESTUDIANTE` (`ID_ESTUDIANTE` ASC) VISIBLE,
  INDEX `ID_MATERIA` (`ID_MATERIA` ASC) VISIBLE,
  CONSTRAINT `nota_formativa_ibfk_1`
    FOREIGN KEY (`ID_ESTUDIANTE`)
    REFERENCES `ispc_g15b`.`cuarto_año` (`ID_ESTUDIANTE`),
  CONSTRAINT `nota_formativa_ibfk_2`
    FOREIGN KEY (`ID_MATERIA`)
    REFERENCES `ispc_g15b`.`materia` (`ID_MATERIA`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
